# Initialization file for the KUKA Fast Research Interface of the Light-Weight Robot IV

[RobotName]
Name=980039

[Priorities]
#Priority range: 1..63
KRCCommunicationThread=63
TimerThread=60
MainThread=60
OutputConsoleThread=5

[ControlValues]
# Cycle time in seconds
CycleTime=0.01

[Logging]
NumberOfLoggingFileEntries=60000
LoggingPath=/home/lwrcontrol/output
LoggingFileName=LWR-Scope.dat